# Switchable at runtime without code edits
llm:
  provider: "openai"            # "openai" | "gemini"
  model: "gpt-4o"
  max_tokens: 256
  # API Configuration
  openai:
    api_key: "${OPENAI_API_KEY}"  # Set via environment variable
    base_url: "https://api.openai.com/v1"  # Optional: for custom endpoints
    organization: "${OPENAI_ORG_ID}"  # Optional: for organization billing
  gemini:
    api_key: "${GEMINI_API_KEY}"  # Set via environment variable
    model: "gemini-1.5-pro-latest"
    safety_settings: "default"  # "default" | "strict" | "permissive"
audio:
  target_fps: 30                # frames‑per‑second for mic chunks
  vad_threshold: 0.55           # energy gate
stt:
  model_path: "whisper.cpp/models/ggml-tiny.en.bin"
  beam_size: 1                  # greedy for speed
tts:
  engine: "piper"               # or "coqui"
  voice: "en_US-amy-medium"
feedback:
  granularity: "phoneme"        # "word" | "phoneme" | "utterance"
plan:
  weeks: 4
  daily_minutes: 10
ui:
  theme: "system"               # auto‑dark/light
database:
  path: "./data/coach.db"
  autosave_interval: 120 # seconds
  analytics_exports: false # dump Parquet via DuckDB when true